import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Solar Cost & Savings | New Era Solar Energy',
  description:
    'Understand solar financing options, potential energy savings, and what the federal tax credit changes mean for homeowners. Get a personalized savings estimate.',
  openGraph: {
    title: 'Solar Cost & Savings | New Era Solar Energy',
    description:
      'Understand solar financing options, potential energy savings, and what the federal tax credit changes mean for homeowners. Get a personalized savings estimate.',
    url: 'https://newerasolarenergy.com/cost-savings',
    siteName: 'New Era Solar Energy',
    locale: 'en_US',
    type: 'website',
  },
};

const faqs = [
  {
    question: 'How much does a solar system cost?',
    answer:
      'Costs vary significantly based on system size, equipment brand, roof type, and location within Florida. We provide a no-obligation, itemized quote after a free home assessment — so you see exactly what you are paying for.',
  },
  {
    question: 'What is net metering?',
    answer:
      'Net metering is a utility billing arrangement where excess solar energy generated by your system and sent back to the grid offsets your electricity bill. Policies, rates, and credit structures vary by state and utility provider. We help you understand how your specific utility handles it.',
  },
  {
    question: 'Are there still tax credits for solar in 2026?',
    answer:
      'Eligible homeowners may qualify for the federal solar tax credit. The credit is currently up to 30% of eligible system costs, but tax benefits depend on your individual situation. Please consult a tax professional. See our tax credit notice on this page.',
  },
  {
    question: 'How long until solar pays for itself?',
    answer:
      'Payback periods vary widely based on financing method, local electricity rates, system size, and how much of your bill the system offsets. We walk you through real projections during your free assessment using your actual utility data.',
  },
  {
    question: 'Can I get financing with no money down?',
    answer:
      'Financing structures vary by lender, program, and credit profile. Some programs offer low or no upfront cost options. We connect you with financing options during your consultation — you choose what works for your situation.',
  },
];

export default function CostSavingsPage() {
  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map((f) => ({
      '@type': 'Question',
      name: f.question,
      acceptedAnswer: {
        '@type': 'Answer',
        text: f.answer,
      },
    })),
  };

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://newerasolarenergy.com' },
      { '@type': 'ListItem', position: 2, name: 'Cost & Savings', item: 'https://newerasolarenergy.com/cost-savings' },
    ],
  };

  return (
    <div className="min-h-screen w-full bg-[#F5F7FA] text-newera-dark-gray">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />

      {/* Breadcrumb */}
      <nav aria-label="Breadcrumb" className="max-w-6xl mx-auto px-6 pt-6 pb-2">
        <ol className="flex items-center gap-2 text-xs text-[#5F6F75] font-sans">
          <li><Link href="/" className="hover:text-[#ff5722] transition-colors">Home</Link></li>
          <li className="text-[#e5e5e5]">/</li>
          <li className="text-newera-dark-gray font-semibold">Cost &amp; Savings</li>
        </ol>
      </nav>

      <main className="max-w-6xl mx-auto px-6 pb-20 flex flex-col gap-16">

        {/* Hero Section */}
        <section className="relative rounded-3xl overflow-hidden bg-newera-dark-blue px-8 md:px-14 py-16 md:py-24 mt-4">
          <div className="absolute inset-0 bg-gradient-to-br from-[#123B5D] via-[#1a4a75] to-[#0a2a42] opacity-95 pointer-events-none" />
          <div className="absolute top-0 right-0 w-96 h-96 bg-[#ff5722]/5 rounded-full -translate-y-1/3 translate-x-1/4 pointer-events-none" />
          <div className="relative z-10 max-w-3xl">
            <span className="inline-block bg-[#ff5722]/20 border border-[#ff5722]/40 text-[#ff5722] px-4 py-1.5 rounded-full text-[11px] font-bold uppercase tracking-widest mb-6">
              Financing &amp; Savings Education
            </span>
            <h1 className="font-poppins font-extrabold text-3xl md:text-5xl lg:text-6xl leading-[1.1] text-white mb-6">
              Understanding the{' '}
              <span className="text-[#ff5722]">Cost and Value</span>{' '}
              of Going Solar
            </h1>
            <p className="text-white/85 text-base md:text-lg leading-relaxed mb-10 max-w-2xl font-sans">
              Solar is a financial decision as much as an energy one. This page breaks down your financing options, what affects your savings, and the current state of federal tax incentives — so you can have an informed conversation with our team.
            </p>
            <Link
              href="/contact"
              className="inline-block bg-[#ff5722] text-white px-8 py-4 rounded-xl font-bold text-sm hover:bg-[#e04a1b] transition-all shadow-[0_8px_30px_rgb(255,138,61,0.3)]"
            >
              Get a Personalized Savings Estimate
            </Link>
          </div>
        </section>

        {/* Financing Options */}
        <section>
          <div className="text-center mb-10">
            <span className="text-[11px] font-bold uppercase text-[#082fa3] tracking-widest block mb-2">How Homeowners Pay</span>
            <h2 className="font-poppins font-bold text-3xl md:text-4xl text-newera-dark-gray">Solar Financing Options Explained</h2>
            <p className="text-[#5F6F75] font-sans mt-4 max-w-2xl mx-auto text-base leading-relaxed">
              There is no single right way to finance solar. Each structure has different cost profiles, ownership implications, and long-term value — we help you compare them clearly.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {[
              {
                icon: '💵',
                title: 'Cash Purchase',
                tag: 'Maximum Ownership',
                desc: 'You purchase the system outright at installation. You own the equipment immediately, avoid financing costs entirely, and receive the full economic benefit of energy production from day one.',
                pros: ['No monthly payments', 'Full system ownership', 'Highest long-term ROI potential'],
                note: 'Best for: Homeowners with available capital who want maximum long-term value.',
              },
              {
                icon: '🏦',
                title: 'Solar Loan',
                tag: 'Own & Finance',
                desc: 'You borrow to purchase the system and pay it off over time. You own the equipment from day one, which means you capture all the value — energy savings and potential home value increase — while spreading cost over time.',
                pros: ['Full ownership from day 1', 'Fixed monthly payment', 'Various term lengths available'],
                note: 'Best for: Homeowners who want ownership benefits without paying all at once.',
              },
              {
                icon: '📄',
                title: 'Solar Lease',
                tag: 'Low Upfront Cost',
                desc: 'You pay a fixed monthly amount to use a solar system that is owned and maintained by a third party. You benefit from solar energy without owning the equipment. Lease payments are typically fixed for the lease term.',
                pros: ['Little to no upfront cost', 'Maintenance included', 'Predictable monthly amount'],
                note: 'Note: You do not own the system. This may affect home sale and tax credit eligibility.',
              },
              {
                icon: '⚡',
                title: 'Power Purchase Agreement (PPA)',
                tag: 'Pay-Per-Kilowatt',
                desc: 'A third party installs a system on your roof at no cost and you agree to purchase the electricity it generates at a set rate per kilowatt-hour — typically lower than your utility rate. Ownership stays with the provider.',
                pros: ['No upfront cost', 'Rate locked below utility', 'Maintenance by provider'],
                note: 'Note: You purchase power, not equipment. Check how this affects your home&apos;s resale.',
              },
            ].map((option) => (
              <div key={option.title} className="bg-white border border-[#e5e5e5] rounded-3xl p-8 shadow-sm hover:shadow-md transition-shadow flex flex-col gap-4">
                <div className="flex items-start justify-between gap-3">
                  <span className="text-4xl">{option.icon}</span>
                  <span className="bg-[#ff5722]/10 border border-[#ff5722]/20 text-[#ff5722] text-[10px] font-bold uppercase tracking-widest px-3 py-1 rounded-full whitespace-nowrap">{option.tag}</span>
                </div>
                <h3 className="font-poppins font-bold text-xl text-newera-dark-gray">{option.title}</h3>
                <p className="text-[#5F6F75] font-sans text-sm leading-relaxed">{option.desc}</p>
                <ul className="flex flex-col gap-2">
                  {option.pros.map((pro) => (
                    <li key={pro} className="flex items-center gap-2 text-xs text-[#5F6F75] font-sans">
                      <svg className="w-3.5 h-3.5 text-[#082fa3] shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
                      </svg>
                      {pro}
                    </li>
                  ))}
                </ul>
                <p className="text-[10px] text-[#5F6F75] font-sans italic border-t border-[#e5e5e5] pt-3 mt-2">{option.note}</p>
              </div>
            ))}
          </div>
        </section>

        {/* IRS Tax Credit Disclaimer */}
        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 text-xs text-amber-800 font-sans leading-relaxed">
          <strong>Federal Solar Tax Credit Notice:</strong> Eligible homeowners may qualify for the federal solar tax credit. The credit is currently up to 30% of eligible system costs, but tax benefits depend on your individual situation. Please consult a tax professional.
        </div>

        {/* Savings Disclaimer */}
        <p className="text-xs text-[#5F6F75] font-sans leading-relaxed mt-2 italic">
          * Savings estimates, return on investment timelines, and financing rates are based on regional averages and typical equipment performance. Actual results vary by homeowner, roof condition, utility rate plan, system size, local policies, credit profile, and other factors. A personalized site assessment and utility analysis is required before any final savings projection.
        </p>

        {/* What Affects Savings */}
        <section className="bg-white border border-[#e5e5e5] rounded-3xl p-8 md:p-12 shadow-sm">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-10 items-start">
            <div>
              <span className="text-[11px] font-bold uppercase text-[#082fa3] tracking-widest block mb-3">Key Variables</span>
              <h2 className="font-poppins font-bold text-2xl md:text-3xl text-newera-dark-gray mb-4">What Influences Solar Savings?</h2>
              <p className="text-[#5F6F75] font-sans text-sm leading-relaxed mb-6">
                Solar savings are highly personalized. No two homes are identical, and any estimate without a real assessment is speculative. Here are the core factors our team evaluates:
              </p>
              <ul className="flex flex-col gap-3">
                {[
                  { label: 'Utility Rate', detail: 'Higher electricity rates mean solar offsets more cost per kWh generated.' },
                  { label: 'Peak Sun Hours', detail: 'Florida averages 5–6 peak sun hours daily — one of the strongest in the US.' },
                  { label: 'Roof Orientation & Pitch', detail: 'South-facing panels at optimal tilt produce the most energy year-round.' },
                  { label: 'System Size', detail: 'Sized to match your usage — over or under-sizing both reduce efficiency.' },
                  { label: 'Energy Consumption Profile', detail: 'How and when you use energy affects how much solar directly offsets your bill.' },
                  { label: 'Net Metering Policy', detail: 'Your utility&apos;s credit rate for exported power significantly affects your ROI.' },
                ].map((item) => (
                  <li key={item.label} className="flex items-start gap-3 bg-[#F5F7FA] border border-[#e5e5e5] rounded-xl p-4">
                    <svg className="w-4 h-4 text-[#ff5722] shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M13 10V3L4 14h7v7l9-11h-7z" />
                    </svg>
                    <div>
                      <p className="font-poppins font-bold text-sm text-newera-dark-gray">{item.label}</p>
                      <p className="text-[#5F6F75] font-sans text-xs mt-0.5 leading-relaxed">{item.detail}</p>
                    </div>
                  </li>
                ))}
              </ul>
            </div>
            <div className="flex flex-col gap-4">
              <div className="bg-newera-dark-blue rounded-2xl p-6 text-white">
                <h3 className="font-poppins font-bold text-lg mb-3">Why a Real Assessment Matters</h3>
                <p className="text-white/80 font-sans text-sm leading-relaxed">
                  Online solar calculators use regional averages and cannot account for your specific roof, your utility plan, or your usage patterns. Our free in-home assessment provides a real analysis based on your actual data — so your savings projection is grounded in reality, not marketing math.
                </p>
              </div>
              <div className="bg-[#F5F7FA] border border-[#e5e5e5] rounded-2xl p-6">
                <h3 className="font-poppins font-bold text-base text-newera-dark-gray mb-2">What We Evaluate in Your Free Assessment</h3>
                <ul className="flex flex-col gap-2 mt-3">
                  {[
                    'Your last 12 months of utility bills',
                    'Roof orientation, pitch, and available area',
                    'Shading analysis throughout the day',
                    'Applicable net metering rates',
                    'Financing options matched to your profile',
                  ].map((item) => (
                    <li key={item} className="flex items-center gap-2 text-xs text-[#5F6F75] font-sans">
                      <svg className="w-3.5 h-3.5 text-[#082fa3] shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
                      </svg>
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* FAQ Section */}
        <section>
          <div className="text-center mb-10">
            <span className="text-[11px] font-bold uppercase text-[#082fa3] tracking-widest block mb-2">Common Questions</span>
            <h2 className="font-poppins font-bold text-3xl md:text-4xl text-newera-dark-gray">Solar Cost &amp; Savings — Frequently Asked Questions</h2>
          </div>
          <div className="flex flex-col gap-4 max-w-3xl mx-auto">
            {faqs.map((faq, idx) => (
              <details
                key={idx}
                className="bg-white border border-[#e5e5e5] rounded-2xl shadow-sm group"
              >
                <summary className="flex items-center justify-between gap-4 px-6 py-5 cursor-pointer font-poppins font-semibold text-newera-dark-gray text-sm md:text-base list-none select-none hover:text-[#ff5722] transition-colors">
                  <span>{faq.question}</span>
                  <span className="shrink-0 w-6 h-6 rounded-full bg-[#F5F7FA] border border-[#e5e5e5] flex items-center justify-center text-[#082fa3] group-open:rotate-45 transition-transform">
                    <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M12 4v16M4 12h16" />
                    </svg>
                  </span>
                </summary>
                <div className="px-6 pb-5 pt-1">
                  <p className="text-[#5F6F75] font-sans text-sm leading-relaxed">{faq.answer}</p>
                </div>
              </details>
            ))}
          </div>
        </section>

        {/* CTA Section */}
        <section className="bg-newera-dark-blue rounded-3xl px-8 md:px-16 py-14 text-center">
          <span className="text-[11px] font-bold uppercase text-[#082fa3] tracking-widest block mb-4">Personalized Analysis</span>
          <h2 className="font-poppins font-bold text-3xl md:text-4xl text-white mb-4">
            Get Numbers That Actually Apply to Your Home
          </h2>
          <p className="text-white/80 font-sans text-base max-w-xl mx-auto mb-8 leading-relaxed">
            Regional averages are a starting point — not a financial plan. Our free assessment delivers a real, itemized savings analysis built around your home, your roof, and your utility account.
          </p>
          <Link
            href="/contact"
            className="inline-block bg-[#ff5722] text-white px-8 py-4 rounded-xl font-bold text-sm hover:bg-[#e04a1b] transition-all shadow-[0_8px_30px_rgb(255,138,61,0.3)]"
          >
            Get a Personalized Savings Estimate
          </Link>
        </section>

      </main>
    </div>
  );
}
