import React from 'react';
import Link from 'next/link';
import { costSavingsPageTranslations } from '@/lib/i18n/pagesContent';
import { Locale } from '@/lib/i18n/language';

interface CostSavingsPageContentProps {
  locale: Locale;
}

export default function CostSavingsPageContent({ locale }: CostSavingsPageContentProps) {
  const isSpanish = locale === 'es';
  const t = isSpanish ? costSavingsPageTranslations.es : costSavingsPageTranslations.en;

  const faqs = isSpanish
    ? [
        {
          question: '¿Cuánto cuesta un sistema solar?',
          answer:
            'Los costos varían notablemente según el tamaño del sistema, la marca del equipo, el tipo de techo y la ubicación en Florida. Brindamos una cotización detallada y sin compromiso después de una evaluación gratuita en el hogar para que vea exactamente por qué paga.',
        },
        {
          question: '¿Qué es la medición neta?',
          answer:
            'La medición neta es un acuerdo de facturación de servicios públicos donde el exceso de energía solar generada por su sistema y devuelta a la red eléctrica compensa su factura de electricidad. Las políticas y tarifas varían por proveedor de luz. Le ayudamos a entender las condiciones de su compañía.',
        },
        {
          question: '¿Aún existen créditos fiscales para la energía solar en 2026?',
          answer:
            'Los incentivos solares federales han cambiado. El Crédito de Energía Limpia Residencial se aplicó a los sistemas elegibles puestos en servicio hasta el 31 de diciembre de 2025. Para los propietarios actuales, los incentivos disponibles pueden depender del tipo de proyecto, la estructura de propiedad, el programa de la empresa de servicios públicos, los incentivos estatales o locales y la situación fiscal. Nuestro equipo puede ayudarle a revisar las opciones actuales, pero los clientes deben confirmar su elegibilidad con un profesional de impuestos calificado. Consulte el aviso de crédito fiscal en esta página.',
        },
        {
          question: '¿Cuánto tiempo pasa antes de que la energía solar se pague sola?',
          answer:
            'Los períodos de retorno de inversión varían según el método de financiamiento, las tarifas eléctricas locales, el tamaño del sistema y el porcentaje de su factura que el sistema compense. Analizaremos las proyecciones en su evaluación gratuita utilizando sus datos de consumo real.',
        },
        {
          question: '¿Puedo obtener financiamiento sin dinero inicial ($0 inicial)?',
          answer:
            'Las estructuras de financiamiento varían según el prestamista, el programa y su perfil crediticio. Algunos programas ofrecen opciones sin costo inicial. Le presentaremos alternativas de financiamiento durante su consulta y usted elegirá lo que mejor se adapte a su caso.',
        },
      ]
    : [
        {
          question: 'How much does a solar system cost?',
          answer:
            'Costs vary significantly based on system size, equipment brand, roof type, and location within Florida. We provide a no-obligation, itemized quote after a free home assessment — so you see exactly what you are paying for.',
        },
        {
          question: 'What is net metering?',
          answer:
            'Net metering is a utility billing arrangement where excess solar energy generated by your system and sent back to the grid offsets your electricity bill. Policies, rates, and credit structures vary by state and utility provider. We help you understand how your specific utility handles it.',
        },
        {
          question: 'Are there still tax credits for solar in 2026?',
          answer:
            'Federal solar incentives have changed. The Residential Clean Energy Credit applied to qualifying systems placed in service through December 31, 2025. For current homeowners, available incentives may depend on the project type, ownership structure, utility program, state/local incentives, and tax situation. Our team can help you review current options, but customers should confirm eligibility with a qualified tax professional. See our tax credit notice on this page.',
        },
        {
          question: 'How long until solar pays for itself?',
          answer:
            'Payback periods vary widely based on financing method, local electricity rates, system size, and how much of your bill the system offsets. We walk you through real projections during your free assessment using your actual utility data.',
        },
        {
          question: 'Can I get financing with no money down?',
          answer:
            'Financing structures vary by lender, program, and credit profile. Some programs offer low or no upfront cost options. We connect you with financing options during your consultation — you choose what works for your situation.',
        },
      ];

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map((f) => ({
      '@type': 'Question',
      name: f.question,
      acceptedAnswer: {
        '@type': 'Answer',
        text: f.answer,
      },
    })),
  };

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: isSpanish ? 'Inicio' : 'Home', item: 'https://newerasolarenergy.com' },
      { '@type': 'ListItem', position: 2, name: isSpanish ? 'Costos y Ahorros' : 'Cost & Savings', item: isSpanish ? 'https://newerasolarenergy.com/es/cost-savings' : 'https://newerasolarenergy.com/cost-savings' },
    ],
  };

  return (
    <div className="min-h-screen w-full bg-[#F9FAFB] text-[#14324b]">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />

      {/* Breadcrumb */}
      <nav aria-label="Breadcrumb" className="max-w-6xl mx-auto px-6 pt-6 pb-2">
        <ol className="flex items-center gap-2 text-xs text-[#4e5257] font-sans">
          <li>
            <Link href={isSpanish ? '/es' : '/'} className="hover:text-[#ff5722] transition-colors">
              {isSpanish ? 'Inicio' : 'Home'}
            </Link>
          </li>
          <li className="text-[#e5e5e5]">/</li>
          <li className="text-[#14324b] font-semibold">
            {isSpanish ? 'Costos y Ahorros' : 'Cost & Savings'}
          </li>
        </ol>
      </nav>

      <main className="max-w-6xl mx-auto px-6 pb-20 flex flex-col gap-16">
        {/* Hero Section */}
        <section className="relative rounded-2xl overflow-hidden bg-[#14324b] px-8 md:px-14 py-16 md:py-24 mt-4">
          <div className="absolute inset-0 bg-gradient-to-br from-[#123B5D] via-[#1a4a75] to-[#0a2a42] opacity-95 pointer-events-none" />
          <div className="absolute top-0 right-0 w-96 h-96 bg-[#ff5722]/5 rounded-full -translate-y-1/3 translate-x-1/4 pointer-events-none" />
          <div className="relative z-10 max-w-3xl">
            <span className="inline-block bg-[#ff5722]/20 border border-[#ff5722]/40 text-[#ff5722] px-4 py-1.5 rounded-full text-[11px] font-bold uppercase tracking-widest mb-6">
              {t.heroTag}
            </span>
            <h1 className="font-poppins font-extrabold text-3xl md:text-5xl lg:text-6xl leading-[1.1] text-white mb-6">
              {isSpanish ? (
                <>Comprendiendo el <span className="text-[#ff5722]">Costo y el Valor</span> del Cambio a Solar</>
              ) : (
                <>Understanding the <span className="text-[#ff5722]">Cost and Value</span> of Going Solar</>
              )}
            </h1>
            <p className="text-white/85 text-base md:text-lg leading-relaxed mb-10 max-w-2xl font-sans">
              {t.heroDesc}
            </p>
            <Link
              href={isSpanish ? '/es/contact' : '/contact'}
              className="inline-block bg-[#ff5722] text-white px-8 py-4 rounded-xl font-bold text-sm hover:bg-[#e04a1b] transition-all shadow-[0_8px_30px_rgb(255,138,61,0.3)] font-sans"
            >
              {t.heroBtn}
            </Link>
          </div>
        </section>

        {/* Financing Options */}
        <section>
          <div className="text-center mb-10">
            <span className="text-[11px] font-bold uppercase text-[#082fa3] tracking-widest block mb-2">
              {isSpanish ? 'Cómo pagan los propietarios' : 'How Homeowners Pay'}
            </span>
            <h2 className="font-poppins font-bold text-3xl md:text-4xl text-[#14324b]">
              {t.optionsTitle}
            </h2>
            <p className="text-[#4e5257] font-sans mt-4 max-w-2xl mx-auto text-base leading-relaxed">
              {t.optionsDesc}
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {t.optionsList.map((option) => (
              <div key={option.title} className="bg-white border border-[#E2E8F0] rounded-2xl p-8 shadow-[0_1px_3px_rgba(0,0,0,0.06),0_1px_2px_rgba(0,0,0,0.04)] hover:shadow-[0_10px_25px_rgba(0,0,0,0.08)] transition-shadow flex flex-col gap-4">
                <div className="flex items-start justify-between gap-3">
                  <span className="text-4xl">{option.icon}</span>
                  <span className="bg-[#ff5722]/10 border border-[#ff5722]/20 text-[#ff5722] text-[10px] font-bold uppercase tracking-widest px-3 py-1 rounded-full whitespace-nowrap">
                    {option.tag}
                  </span>
                </div>
                <h3 className="font-poppins font-bold text-xl text-[#14324b]">{option.title}</h3>
                <p className="text-[#4e5257] font-sans text-sm leading-relaxed">{option.desc}</p>
                <ul className="flex flex-col gap-2">
                  {option.pros.map((pro) => (
                    <li key={pro} className="flex items-center gap-2 text-xs text-[#4e5257] font-sans">
                      <svg className="w-3.5 h-3.5 text-[#082fa3] shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
                      </svg>
                      {pro}
                    </li>
                  ))}
                </ul>
                <p className="text-[10px] text-[#4e5257] font-sans italic border-t border-[#E2E8F0] pt-3 mt-2">{option.note}</p>
              </div>
            ))}
          </div>
        </section>

        {/* IRS Tax Credit Disclaimer */}
        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 text-xs text-amber-800 font-sans leading-relaxed">
          <strong>{isSpanish ? 'Aviso sobre el Crédito Fiscal Federal para Energía Solar:' : 'Federal Solar Tax Credit Notice:'}</strong> {isSpanish ? 'Los incentivos solares federales han cambiado. El Crédito de Energía Limpia Residencial se aplicó a los sistemas elegibles puestos en servicio hasta el 31 de diciembre de 2025. Para los propietarios actuales, los incentivos disponibles pueden depender del tipo de proyecto, la estructura de propiedad, el programa de la empresa de servicios públicos, los incentivos estatales o locales y la situación fiscal. Nuestro equipo puede ayudarle a revisar las opciones actuales, pero los clientes deben confirmar su elegibilidad con un profesional de impuestos calificado.' : 'Federal solar incentives have changed. The Residential Clean Energy Credit applied to qualifying systems placed in service through December 31, 2025. For current homeowners, available incentives may depend on the project type, ownership structure, utility program, state/local incentives, and tax situation. Our team can help you review current options, but customers should confirm eligibility with a qualified tax professional.'}
        </div>

        {/* Savings Disclaimer */}
        <p className="text-xs text-[#4e5257] font-sans leading-relaxed mt-2 italic">
          {t.savingsDisclaimer}
        </p>

        {/* What Affects Savings */}
        <section className="bg-white border border-[#E2E8F0] rounded-2xl p-8 md:p-12 shadow-sm">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-10 items-start">
            <div>
              <span className="text-[11px] font-bold uppercase text-[#082fa3] tracking-widest block mb-3">
                {t.varsTag}
              </span>
              <h2 className="font-poppins font-bold text-2xl md:text-3xl text-[#14324b] mb-4">
                {t.varsTitle}
              </h2>
              <p className="text-[#4e5257] font-sans text-sm leading-relaxed mb-6">
                {t.varsDesc}
              </p>
              <ul className="flex flex-col gap-3">
                {t.variables.map((item) => (
                  <li key={item.label} className="flex items-start gap-3 bg-[#F9FAFB] border border-[#E2E8F0] rounded-xl p-4">
                    <svg className="w-4 h-4 text-[#ff5722] shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M13 10V3L4 14h7v7l9-11h-7z" />
                    </svg>
                    <div>
                      <p className="font-poppins font-bold text-sm text-[#14324b]">{item.label}</p>
                      <p className="text-[#4e5257] font-sans text-xs mt-0.5 leading-relaxed">{item.detail}</p>
                    </div>
                  </li>
                ))}
              </ul>
            </div>
            <div className="flex flex-col gap-4">
              <div className="bg-[#14324b] rounded-2xl p-6 text-white">
                <h3 className="font-poppins font-bold text-lg mb-3">
                  {isSpanish ? 'Por qué es importante un análisis real' : 'Why a Real Assessment Matters'}
                </h3>
                <p className="text-white/80 font-sans text-sm leading-relaxed">
                  {t.expectDesc}
                </p>
              </div>
              <div className="bg-[#F9FAFB] border border-[#E2E8F0] rounded-2xl p-6">
                <h3 className="font-poppins font-bold text-base text-[#14324b] mb-2">
                  {t.expectListTitle}
                </h3>
                <ul className="flex flex-col gap-2 mt-3">
                  {t.expectList.map((item) => (
                    <li key={item} className="flex items-center gap-2 text-xs text-[#4e5257] font-sans">
                      <svg className="w-3.5 h-3.5 text-[#082fa3] shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
                      </svg>
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* FAQ Section */}
        <section>
          <div className="text-center mb-10">
            <span className="text-[11px] font-bold uppercase text-[#082fa3] tracking-widest block mb-2">
              {isSpanish ? 'Preguntas comunes' : 'Common Questions'}
            </span>
            <h2 className="font-poppins font-bold text-3xl md:text-4xl text-[#14324b]">
              {t.faqTitle}
            </h2>
          </div>
          <div className="flex flex-col gap-4 max-w-3xl mx-auto">
            {faqs.map((faq, idx) => (
              <details key={idx} className="bg-white border border-[#E2E8F0] rounded-2xl shadow-sm group">
                <summary className="flex items-center justify-between gap-4 px-6 py-5 cursor-pointer font-poppins font-semibold text-[#14324b] text-sm md:text-base list-none select-none hover:text-[#ff5722] transition-colors">
                  <span>{faq.question}</span>
                  <span className="shrink-0 w-6 h-6 rounded-full bg-[#F9FAFB] border border-[#E2E8F0] flex items-center justify-center text-[#082fa3] group-open:rotate-45 transition-transform">
                    <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M12 4v16M4 12h16" />
                    </svg>
                  </span>
                </summary>
                <div className="px-6 pb-5 pt-1">
                  <p className="text-[#4e5257] font-sans text-sm leading-relaxed">{faq.answer}</p>
                </div>
              </details>
            ))}
          </div>
        </section>

        {/* CTA Section */}
        <section className="bg-[#14324b] rounded-2xl px-8 md:px-16 py-14 text-center">
          <span className="text-[11px] font-bold uppercase text-[#082fa3] tracking-widest block mb-4">
            {t.ctaBoxTag}
          </span>
          <h2 className="font-poppins font-bold text-3xl md:text-4xl text-white mb-4">
            {t.ctaBoxTitle}
          </h2>
          <p className="text-white/80 font-sans text-base max-w-xl mx-auto mb-8 leading-relaxed">
            {t.ctaBoxDesc}
          </p>
          <Link
            href={isSpanish ? '/es/contact' : '/contact'}
            className="inline-block bg-[#ff5722] text-white px-8 py-4 rounded-xl font-bold text-sm hover:bg-[#e04a1b] transition-all shadow-[0_8px_30px_rgb(255,138,61,0.3)] font-sans"
          >
            {t.ctaBoxBtn}
          </Link>
        </section>
      </main>
    </div>
  );
}

